version: "3.8"

services:
  client:
    container_name: drater-client
    image: drater-client
    build: ./client
    ports:
      - "80:80"
    networks:
      - drater-network
  server:
    container_name: drater-server
    image: drater-server
    build: ./server
    ports:
      - "8080:8080"
    networks:
      - drater-network
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=False
      - LSTM_HOST=lstm:50051
      - NLP_HOST=nlp:50052
  lstm:
    container_name: drater-lstm
    image: drater-lstm
    build: ./lstm
    ports:
      - "50051:50051"
    networks:
      - drater-network
  nlp:
    container_name: drater-nlp
    image: drater-nlp
    build: ./nlp
    ports:
      - "50052:50052"
    networks:
      - drater-network
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY} 
volumes:
  drater:
networks:
  drater-network:
    driver: bridge
